backend/project/prehrana/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import DetailView
from prehrana.models import Restaurant
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^locals/(?P<restaurant_id>\d+)$', views.locals, name='locals', ),
    url(r'^locals/$', views.locals, name='locals', ),
    url(r'^login/$', views.login_view , name=""),
    url(r'^logout/$', views.logout_user, name=""),

    url(r'^contact/$', views.contact, name='contact'),
    #url(r'^logout/', views.logout_user, name='logout'),
    #url(r'^article/(?P<article_id>[0-9]+)/$', views.article_view, name='article_view'),
    #url(r'^article/(?P<article_id>[0-9]+)/edit/$', views.article_edit, name='article_edit'),
]

backend/project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('prehrana.urls')),
]

backend/project/prehrana/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime



class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, default="0.0")
    latitude = models.DecimalField(max_digits=9, decimal_places=6, default="0.0")
    price = models.FloatField("student meal price", default=-1)
    rating = models.FloatField("average rating", default=-1)

    vegi = models.BooleanField( default=False)
    delivery = models.BooleanField( default=False)
    sallad = models.BooleanField( default=False)
    pizza = models.BooleanField(default=False)
    lunch = models.BooleanField( default=False)
    fastfood = models.BooleanField( default=False)
    invalid_friendly = models.BooleanField( default=False)

    def __str__(self):
        return self.name


class Menu(models.Model):
    food = models.TextField("menu")
    date = models.DateField()
    restaurant_id = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ('edit_menu', 'Can edit the menus'),
        )




class Feedback(models.Model):
    rating = models.IntegerField()
    comment = models.TextField()
    restaurant_id = models.ForeignKey(Restaurant)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user_id)+" "+str(self.rating)+" "+str(self.restaurant_id)


from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver




@receiver(post_delete, sender=Feedback)
def update_rating(sender, instance, **kwargs):
    restaurant = instance.restaurant_id
    feedbacks = Feedback.objects.filter(restaurant_id=restaurant.id)
    restaurant.rating = sum([object.rating for object in feedbacks])/len(feedbacks)
    print([object.rating for object in feedbacks])
    restaurant.save()


@receiver(post_save, sender=Feedback)
def update_rating2(sender, instance, **kwargs):
    restaurant = instance.restaurant_id
    feedbacks = Feedback.objects.filter(restaurant_id=restaurant.id)
    restaurant.rating = sum([object.rating for object in feedbacks])/len(feedbacks)
    print([object.rating for object in feedbacks])
    restaurant.save()

backend/project/prehrana/forms.py
from django import forms
import re
from prehrana.models import *




class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)


class RegistrationForm(forms.Form):
    new_username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)
    password_repeated = forms.CharField(max_length=50, widget=forms.PasswordInput)


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ["user_id", "rating", "comment", "restaurant_id"]


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ["date", "food", "restaurant_id"]


class SearchForm(forms.Form):
    filter = forms.CharField(min_length=7)
    criteria = forms.CharField(min_length=1)
    loc = forms.CharField()

    def is_valid(self):
        if super(SearchForm, self).is_valid():
            if self.cleaned_data['filter'].strip("tf") == "":
                if self.cleaned_data['criteria'] in ["1", "2"]:
                    if len(re.findall(r"(-?\d{1,2}\.\d{6}),(-?\d{1,2}\.\d{6}$)", self.cleaned_data['loc']))==1:
                        return True
        return False

backend/project/prehrana/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import math
import datetime
from prehrana.forms import LoginForm, RegistrationForm, FeedbackForm, MenuForm, SearchForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views
from prehrana.models import Restaurant, Feedback, Menu
from django.contrib.auth.models import User
import logging

log = logging.getLogger("prehrana")

# Create your views here.

app_name = 'prehrana'
from django.views.decorators.csrf import csrf_exempt

def login_view(request):
    """handle the login and registration requests"""
    error_view = views.login(request, template_name="prehrana/login.html",
                             extra_context={"message": "vneseni podatki niso veljavni"})

    if request.method == "POST":
        if request.POST.get('new_username', False):
            # registration form was submited
            form = RegistrationForm(request.POST)
            if form.is_valid():
                user = User.objects.create_user(username=form.cleaned_data['new_username'],
                                                password=form.cleaned_data['password'])
            else:
                return error_view
        else:
            # login form was submited
            form = LoginForm(request.POST)
            if form.is_valid():
                user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            else:
                return error_view
        if user is not None:
            # request was OK
            #login(request, user)
            return HttpResponseRedirect("/index/")
        else:
            return error_view
    return views.login(request, template_name="prehrana/login.html")


def index(request):
    return render(request, "prehrana/index.html", {"restaurant_list": Restaurant.objects.all().
                  order_by("-rating")[:5]})


def search(request):
    """handles search requests"""
    form = SearchForm(request.GET)
    if form.is_valid():
        return search_nearest(request)
    return render(request, "prehrana/search.html", {"restaurant_list": Restaurant.objects.all().
                  order_by("-rating")[:5]})


def search_nearest(request):
    """handles search for nearest restaurants"""
    filter_names = ["vegi", "lunch", "pizza", "sallad", "delivery", "fastfood", "invalid_friendly"]
    filters = {n: True for n, x in zip(filter_names, list(request.GET.get('filter', ''))) if x == "t"}
    criteria = request.GET.get('criteria', '')
    location = request.GET.get('loc', '').split(",")
    x = float(location[0])
    y = float(location[1])
    distances = [(math.sqrt((x - float(rest.longitude)) ** 2 + (y - float(rest.latitude)) ** 2), rest)
                 for rest in Restaurant.objects.filter(**filters)]
    restaurants = sorted([rest for _, rest in sorted(distances)[:5]],
                         key=(lambda x: x.price) if criteria == "1" else (lambda x: -x.rating))
    return render(request, "prehrana/search.html", {"restaurant_list": restaurants})


def locals(request, restaurant_id=1):
    """handles the locals view and feedback or menu POST requests"""
    if request.method == "POST" and request.user.is_authenticated:
        if request.POST.get('food', False):
            # comment was submited
            form_data = request.POST.dict()
            form_data["restaurant_id"] = restaurant_id
            form_data["user_id"] = request.user.id
            form = FeedbackForm(form_data)
            if form.is_valid():
                log.debug("user {} submited a feedback for restaurant {}: [rating={}, comment={}]".
                          format(request.user.id, restaurant_id, form_data["rating"], form_data["comment"]))
                form.save()
        elif request.user.has_perm("prehrana.edit_menu"):
            # menu was submited:
            form_data = request.POST.dict()
            form_data["restaurant_id"] = restaurant_id
            form = MenuForm(form_data)
            if form.is_valid():
                log.debug("user {} submited a menu for restaurant {}: [food={}]"
                          .format(request.user.id, restaurant_id, form_data["food"]))
                form.save()

    if request.GET.get('localName', False):
        restaurant_id = Restaurant.objects.get(name=request.GET.get('localName', '')).id

    context = {}
    context["restaurant_names"] = [r.name for r in Restaurant.objects.all()]
    context["restaurant"] = Restaurant.objects.get(pk=restaurant_id)
    context["feedbacks"] = Feedback.objects.filter(restaurant_id=restaurant_id)
    context["menus"] = Menu.objects.filter(restaurant_id=restaurant_id, date=datetime.date.today())
    return render(request, "prehrana/locals.html", context)


def contact(request):
    """contact page"""
    return render(request, "prehrana/contact.html")


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

backend/project/prehrana/templates/prehrana/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Prehrana</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href={% static 'prehrana/layout.css' %}>
    <script src={% static 'prehrana/scripts.js' %}></script>
</head>
<body>


<header>
    <h1>Študentska prehrana</h1>
    <ul class="menu">
        <li><a href="/index/" id = "index">Domov</a></li>
        <li><a href="/search/" id = "search">Iskanje</a></li>
        <li><a href="/locals/" id = "local">Lokali</a></li>
		
        <li class="right"><a href="/contact/" id = "contact">Kontakt</a></li>

        {% if user.is_authenticated %}
            <li class="right"><a href="/logout/" id = "login">{{ user.username }} : Odjava</a></li>
        {% else %}
            <li class="right"><a href="/login/" id = "login">Prijava</a></li>
        {% endif %}

    </ul>
</header>




{% block content %}
{% endblock %}

<div class="banner"></div>

<footer>Študentska prehrana</footer>


</body>
</html>

backend/project/prehrana/templates/prehrana/contact.html
{% extends "prehrana/base.html" %}

{% block content %}
<div class="flex-container">

    <script>
        document.getElementById("contact").style.backgroundColor = "#4CAF50";
    </script>

    <div style="text-align: center;">
        <br>
        <br>
        <br>
        <br>
        <h3>Študentska prehrana</h3>
        <h3>Janez Novak</h3>
        <h3>Tržaska ulica 23</h3>
        <h3>1000 ljubljana</h3>
        <h3>janez@gmail.com</h3>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>

    </div>

</div>

{% endblock %}

backend/project/prehrana/templates/prehrana/index.html
{% extends "prehrana/base.html" %}
{% load static %}
{% block content %}

    <script>
        document.getElementById("index").style.backgroundColor = "#4CAF50";
        window.addEventListener("load", init, false);
    </script>

    <div class="flex-container">

        <div class="column1">
            <div>

                {% include "prehrana/includes/search_form.html" %}

                <br>
                <div class="search-container">
                    <h2>Priporočamo:</h2>
                    <a class="fill" href="/locals/1">
                        <img src="{% static "prehrana/img/oglas.jpg"%}" title="Oglaševana gostilna" alt="Oglaševana gostilna">
                    </a>
                </div>
            </div>
        </div>
        <div class="column2">
            <h2>Priljubljeno:</h2>
            {% include "prehrana/includes/restaurant_list.html" %}

        </div>
    </div>

{% endblock %}

backend/project/prehrana/templates/prehrana/locals.html
{% extends "prehrana/base.html" %}
{% load static %}
{% block content %}
    <script>
        window.addEventListener("load", initLocals, false);
        document.getElementById("local").style.backgroundColor = "#4CAF50";
    </script>

    <form action="search" class="flex-container" id="searchLocalsForm">
        <input required name="localName" type="text" placeholder="Vnesite ime lokala za iskanje"
               class="search input green"
               list="locals" id="searchLocalsInput">
        <datalist id="locals">
            {% for name in restaurant_names %}
                <option value="{{ name }}" id="{{ name }}">
            {% endfor %}
        </datalist>

        <input type="submit" class="search btn green" value="Išči" style="max-width:90px; text-align: center">
    </form>

    <div class="flex-container">

        <div class="column1">

            <div class="search-container local">
                <img src="{% static "prehrana/img/lokal1.png" %}" alt="Slika lokala"/>
                <h3>{{ restaurant.name }}</h3>
                <p hidden class="coordinates">45.957485,14.107477</p>
                <p>naslov: <b>{{ restaurant.address }}</b></p>
                <p>doplačilo: <b>{{ restaurant.price }}€</b></p>
                <p>ocena: <b>{{ restaurant.rating }}</b></p>
            </div>
        </div>

        <div class="column2">
            <div class="search-container" id="map" style="min-height: 405px;"></div>
        </div>
    </div>

    <div class="flex-container buttonGroup" id="selection">
        <a class="search btn green selected" id="menu">Jedilnik</a>
        <a class="search btn green" id="comments">Komentarji</a>
    </div>

    <div class="flex-container" id="food">
        <ul class="list unclickable" id="menu-list" style="display: block">
            <li>
                {% if perms.prehrana.edit_menu %}

                    <form action="" id="commentForm" method="post">
                    {% csrf_token %}
                        <input type="date" name="date" required class = "search area green">
                        <textarea name="food" class="search area green" required cols="60"
                                  placeholder="vnesite jedilnik za izbran datum"></textarea>
                        <input type="submit" class="search btn green" value="Vnesi">

                    </form>

                {% endif %}
            </li>

            {% for menu in menus %}
                <li>
                    <pre>{{ menu.food }}</pre>
                </li>
            {% endfor %}
        </ul>


        <ul class="list unclickable" id="comment-list" style="display: none">

            <li>
                {% if user.is_authenticated %}

                    <form action="" id="commentForm" method="post">
                        {% csrf_token %}
                        <select title="ocena" class="search area green" name="rating"  required>
                            <option value="1">ocena: 1</option>
                            <option value=2>ocena: 2</option>
                            <option value=3>ocena: 3</option>
                            <option value="4">ocena: 4</option>
                            <option value="5">ocena: 5</option>
                        </select>
                        <textarea name="comment" class="search area green" cols="60"
                                  placeholder="če želite, vnesite komentar"></textarea>
                        <input type="submit" class="search btn green" value="Oceni">



                    </form>
                {% else %}
                    <p>Prijavite se za oddajo komentarjev</p>

                {% endif %}
            </li>


            {% for feedback in feedbacks %}
                <li>
                    <b>{{ feedback.user_id.username }}:</b>
                    <ul>
                        <li>
                            <pre>{{ feedback.comment }}</pre>
                        </li>
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBddplbofVTpo0_3xeXmXPsiGsxvwWg8q4&callback=initMap">
    </script>

{% endblock %}

backend/project/prehrana/templates/prehrana/login.html
{% extends "prehrana/base.html" %}

{% block content %}
<div class="flex-container">

    <script>
        document.getElementById("login").style.backgroundColor = "#4CAF50";
    </script>






		<form method="post" action="">
		<p>Obstoječi uporabnik:</p>
			{% csrf_token %}
			<table>
				<tr>
					<td>{{ form.username.label_tag }}</td>
					<td>{{ form.username }}</td>
				</tr>
				<tr>
					<td>{{ form.password.label_tag }}</td>
					<td>{{ form.password }}</td>
				</tr>
		   </table>

		   <input type="submit" value="login" />
	   </form>
	   
	   
	   <form method="post" action="">
	   <p>Nov uporabnik:</p>
			{% csrf_token %}
			<table>
				<tr>
					<td><label for="id_username">Username:</label></td>
					<td><input autofocus="" id="id_username" maxlength="254" name="new_username" type="text" required /></td>
				</tr>
				<tr>
					<td><label for="id_new_password">Password:</label></td>
					<td><input id="id_new_password" name="password" type="password" required /></td>
				</tr>
				<tr>
					<td><label for="id_password_repeated">Password:</label></td>
					<td><input id="id_password_repeated" name="password_repeated" type="password" required onfocusout="validatePassword()"/></td>
				</tr>
		   </table>
	
		   <input type="submit" value="login" />
	   </form>

    <div><p>{{ message }}</p><br></div>

    <script>

        var password = document.getElementById("id_new_password");
        var confirm_password = document.getElementById("id_password_repeated");

        function validatePassword(){
          if(password.value != confirm_password.value) {
            confirm_password.value="";
          }
        }
        console.log(password);
        password.onchange = validatePassword;
        confirm_password.onfocusout = validatePassword;

    </script>


</div>

{% endblock %}

backend/project/prehrana/templates/prehrana/search.html
{% extends "prehrana/base.html" %}

{% block content %}

    <script>
    document.getElementById("search").style.backgroundColor = "#4CAF50";
        window.addEventListener("load", init, false);
    </script>

    <div class="flex-container">
        <div class="column1">

            {% include "prehrana/includes/search_form.html" %}

            <br>
            <div class="search-container" id="map"></div>
        </div>
        <div class="column2">
        <h2>Zadetki:</h2>
        {% include "prehrana/includes/restaurant_list.html" %}

        </div>
    </div>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBddplbofVTpo0_3xeXmXPsiGsxvwWg8q4&callback=initMap">
    </script>

{% endblock %}